In [1]:
import array as arr
import numpy as np

In [2]:
a=arr.array('i',[10,20,30,40])

In [3]:
print("The elements in array are:")
for i in a:
    print(i)

The elements in array are:
10
20
30
40


In [4]:
from array import *
a=array('i',[10,20,30,40])
print("The elements in array are:")
for i in a :
    print(i)

The elements in array are:
10
20
30
40


In [5]:
import numpy
arr1=numpy.array([10,20,30,40])
arr1

array([10, 20, 30, 40])

In [6]:
import numpy as np
arr2=np.array([10,20,30,40])
arr2

array([10, 20, 30, 40])

In [7]:
from numpy import *
arr3=array([10,20,30,40])
arr3

array([10, 20, 30, 40])

In [8]:
a1=np.array(["hyderabad,delhi,mumbai,chennai"])
print(a1)

['hyderabad,delhi,mumbai,chennai']


In [9]:
a2=np.linspace(0,20,5)
print(a2)

[ 0.  5. 10. 15. 20.]


In [10]:
a2

array([ 0.,  5., 10., 15., 20.])

In [11]:
a1=np.arange(1,9)
a1

array([1, 2, 3, 4, 5, 6, 7, 8])

In [13]:
a2=np.arange(0,20,2)
a2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [14]:
a1[0]

1

In [15]:
a2[3]

6

In [16]:
a1[1:4]

array([2, 3, 4])

In [17]:
a2[3:7]

array([ 6,  8, 10, 12])

In [18]:
a=np.array([10,20,30,40])
a

array([10, 20, 30, 40])

In [20]:
a+5

array([15, 25, 35, 45])

In [21]:
a-3

array([ 7, 17, 27, 37])

In [22]:
a*2

array([20, 40, 60, 80])

In [23]:
a/5

array([2., 4., 6., 8.])

In [24]:
MEAN=np.mean(a)
MEAN

25.0

In [25]:
MEDIAN=np.median(a)
MEDIAN

25.0

In [26]:
variance=np.var(a)
variance

125.0

In [27]:
standarddeviation=np.std(a)
standarddeviation

11.180339887498949

In [28]:
a1=array([10,20,30,40])
print("1D")
print(a1)
a2=array([[1,2,3],[4,5,6]])
print("2D")
print(a2)
a3=array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print("3D")
print(a3)

1D
[10 20 30 40]
2D
[[1 2 3]
 [4 5 6]]
3D
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [29]:
a1=np.array([1,2,3,4])
a1.ndim

1

In [30]:
a2=np.array([[1,2,3],[4,5,6]])
a2.ndim

2

In [31]:
a1.shape

(4,)

In [32]:
a2.shape

(2, 3)

In [33]:
a1.size

4

In [37]:
a2.size

6

In [38]:
arr1=arange(10)

In [39]:
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [40]:
arr1.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [41]:
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])